version: '3.8'

networks:
  geo_default:
    external:
      name: geo_default

services:
  web:
    container_name: sru-traker-web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: production
    command: serve -s build -l 3000
    # stdin_open: true
    # tty: true
    restart: unless-stopped
    ports:
      - "3000:3000"
    # volumes:
    #   - ./web:/usr/src/app
    #   - .:/usr/scr/app/node_modules
    networks:
      - geo_default
