version: '3'

services:
  service-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: service-web-prod
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
