version: '3.8'

# networks:
#   geo_default:
#     external:
#       name: geo_default

services:
  api:
    container_name: sru-traker-web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/scr/app
      - ./node_modules:/usr/scr/app/node_modules
    # networks:
    #   - geo_default
